-- GuaJokesAddon.lua

-- Table of Gua jokes
local jokes = {
    "Superman wears Gua pajamas.",
    "Gua can divide by zero.",
    "Gua can slam a revolving door.",
    "Gua counted to infinity. Twice.",
    "Gua doesn’t do push-ups. He pushes the Earth down.",
    "When Gua goes swimming, sharks call it a vacation.",
    "Gua can unscramble an egg.",
    "The boogeyman checks his closet for Gua before going to bed.",
    "Gua can hear sign language.",
    "Death once had a near-Gua experience.",
    "Gua can make a Happy Meal cry.",
    "Gua once climbed Mt. Everest in 10 minutes. He spent 9 of those minutes building a snowman.",
    "Gua can light a fire by rubbing two ice cubes together.",
    "Gua can solve a Rubik’s Cube in one move: smashing it.",
    "Gua once made a rock bleed.",
    "Ghosts tell stories about Gua around the campfire.",
    "Gua doesn’t wear a watch; he decides what time it is.",
    "Gua’s tears cure cancer. Too bad he has never cried.",
    "Gua can sneeze with his eyes open.",
    "Gua can kill two stones with one bird.",
    "Gua once won a game of Connect Four in three moves.",
    "Gua doesn’t read books; he stares them down until they give him the information.",
    "Gua can make onions cry.",
    "Gua can delete the recycling bin.",
    "Gua knows Victoria’s secret.",
    "Gua once won a game of rock-paper-scissors using only his fist.",
    "Gua can dribble a bowling ball.",
    "Gua can hear colors.",
    "Gua can touch MC Hammer.",
    "Gua can bake a cake in an ice cube tray.",
    "Gua can speak Braille.",
    "Gua can build a snowman out of rain.",
    "Gua can make a jalapeño cry.",
    "Gua can moonwalk forwards.",
    "When Gua enters the room, Wi-Fi signals bow to him.",
    "Gua can hear your thoughts.",
    "Gua once beat a computer at chess—by telling it to give up.",
    "Gua doesn’t mow his lawn; he dares the grass to grow.",
    "Gua can make a fish drown.",
    "Gua’s smile once brought a mannequin to life.",
    "Gua can do a wheelie on a unicycle.",
    "Gua doesn't flush the toilet; he scares the stuff down.",
    "Gua once gave a cat a bath. It still hasn't stopped thanking him.",
    "Gua knows how many licks it takes to get to the center of a Tootsie Pop.",
    "Gua can strangle you with a cordless phone.",
    "Gua can leave a message before the beep.",
    "Gua doesn’t get sunburned; the sun gets Gua-burned.",
    "Gua once won a game of poker with Uno cards.",
    "Gua can divide by zero and get a remainder.",
    "Gua once made a weeping willow laugh.",
    "Gua can watch 60 minutes in 20 seconds.",
    "When Gua crosses the street, the cars stop and look both ways.",
    "Gua can lift a ton with one finger. His pinky.",
    "Gua doesn't measure things; things adjust to Gua's preferences.",
    "Gua once made the Mona Lisa frown.",
    "Gua can draw a straight line with a ruler—without using the ruler.",
    "Gua doesn’t need a parachute to skydive. He just decides when to land.",
    "Gua’s calendar skips April Fool’s Day—because no one fools Gua.",
    "Gua can unscramble a scrambled channel on TV.",
    "Gua doesn’t need keys to open doors. Doors just unlock themselves for him.",
    "Gua can turn off a light by clapping… with one hand.",
    "Gua can parallel park a train.",
    "Gua can put out a fire using gasoline.",
    "Gua can win a marathon without taking a single step.",
    "Gua once scored a goal in hockey. Without a puck.",
    "Gua can split the atom—with his bare hands.",
    "Gua can jump-start a car with his mind.",
    "Gua’s voice can shatter glass, but only when he wants it to.",
    "Gua can plug in a USB on the first try, every time.",
    "Gua can play a game of tennis with the net still up.",
    "Gua once threw a boomerang that never came back. The boomerang was scared.",
    "Gua doesn’t need a GPS; the roads follow him.",
    "Gua once won hide and seek against the entire world.",
    "Gua can find Waldo in one look.",
    "When Gua turns on a light, darkness gets out of his way.",
    "Gua can roundhouse kick a tornado.",
    "Gua can make time stand still by looking at the clock.",
    "Gua’s reflection won’t look at him out of respect.",
    "Gua can walk on water—and swim through land.",
    "Gua can start a fire with water.",
    "Gua can eat a whole cake before anyone has a chance to cut it.",
    "Gua can whistle in all languages.",
    "Gua doesn’t dodge bullets; bullets dodge Gua.",
    "Gua once beat gravity in an arm-wrestling match.",
    "Gua can melt ice by staring at it.",
    "Gua can remember the future.",
    "Gua’s footprints alone can be sold as artwork.",
    "Gua once bowled a perfect game—in mini-golf.",
    "Gua can pick a lock using only a paperclip and a toothpick.",
    "Gua's handshake has made professional boxers retire.",
    "Gua can alphabetize numbers.",
    "Gua once played Jenga with Mount Everest. It’s now the Himalayas.",
    "Gua doesn’t shave. His beard naturally falls off when it’s time.",
    "Gua once made a Happy Meal unhappy.",
    "Gua can cut through a hot knife with butter.",
    "Gua can tie his shoes with his feet.",
    "Gua once made an onion cry just by smiling at it.",
    "Gua can do a full push-up without bending his arms.",
    "Gua can touch time.",
    "Gua doesn't wait for opportunity to knock; he knocks opportunity down.",
    "Gua can turn invisible simply by standing still.",
    "Gua once won an Olympic gold medal without competing.",
    "Gua doesn’t need a ladder; the sky lowers for him.",
    "Gua can win a staring contest with the sun.",
    "Gua once squeezed orange juice out of an apple.",
    "Gua can tune a piano by snapping his fingers.",
    "Gua once turned a diamond back into coal—just because.",
    "Gua doesn't do yoga; the universe stretches to accommodate him.",
    "Gua can fold a fitted sheet perfectly in seconds.",
    "Gua can find the square root of a negative number.",
    "Gua can solve a maze by looking at it.",
    "Gua’s phone never drops calls—it drops networks.",
    "Gua doesn’t go to the gym. The gym comes to him.",
    "Gua can stop traffic—by blinking.",
    "Gua can microwave a steak with cold air.",
    "Gua can solve a crossword puzzle without reading the clues.",
    "Gua doesn’t iron his clothes; his body heat presses them perfectly.",
    "Gua’s handshake once turned a rock into sand.",
    "Gua can win a game of Monopoly with one roll of the dice.",
    "Gua can sneeze with his mouth closed.",
    "Gua can clap with one hand.",
    "Gua once ran around the world just to see himself finish the race.",
    "Gua’s frown can move mountains.",
    "Gua can sneeze and burp at the same time—and remain composed.",
    "Gua can speak all languages, even the ones that don’t exist yet.",
    "Gua can stop a hurricane by blowing a kiss.",
    "Gua can open a locked door with just a glance.",
    "Gua doesn’t need maps; the earth arranges itself for him.",
    "Gua can make a diamond by squeezing carbon with his eyelids.",
    "Gua can beatbox in perfect harmony.",
    "Gua can divide by one and get zero—just to prove a point.",
    "Gua can high-five himself and make it sound like thunder.",
    "Gua can predict tomorrow’s weather, today.",
    "Gua can turn paper into scissors by staring at it.",
    "Gua can make water float in mid-air.",
    "Gua can put a square peg into a round hole.",
    "Gua once made a brick house out of straw.",
    "Gua can win at chess in one move—with a checker.",
    "Gua can paint the Mona Lisa using only finger paints.",
    "Gua once played Russian Roulette with a fully loaded gun—and won.",
    "Gua can run faster than light and still stop for a coffee break.",
    "Gua can peel a banana using only his mind.",
    "Gua doesn’t break a sweat; sweat breaks itself for Gua.",
    "Gua can type faster than a supercomputer can compute.",
    "Gua can juggle fire—and water.",
    "Gua can freeze time and still be early to an appointment.",
    "Gua once built a snowman out of sand.",
    "Gua doesn’t need a GPS; lost people find Gua.",
    "Gua’s smile can power a city for a week.",
    "Gua can turn glass back into sand.",
    "Gua can create a black hole just by flexing.",
    "Gua can make the sky blue by whistling.",
    "Gua can flip a coin and make it land on its edge.",
    "Gua can swim through lava and not get burned.",
    "Gua can make time go backward by taking a step forward.",
    "Gua can turn a cactus into a rose bush with a wink.",
    "Gua can play ping-pong with a bowling ball.",
    "Gua can drink boiling water and turn it into ice.",
    "Gua can turn coal into diamonds with a gentle hug.",
    "Gua once solved world hunger—by eating.",
    "Gua can open a door just by knocking on the wall next to it.",
    "Gua’s hair can cut through steel.",
    "Gua can split the Red Sea with a smile.",
    "Gua can jump to the moon and back before breakfast.",
    "Gua can make the wind blow in any direction he chooses.",
    "Gua can stop an avalanche by snapping his fingers.",
    "Gua once gave CPR to a volcano and stopped it from erupting.",
    "Gua can inflate a tire just by breathing on it.",
    "Gua can watch a full season of a show in one episode.",
    "Gua can make gravity take the day off.",
    "Gua can knit a sweater out of fog.",
    "Gua can boil water just by staring at it.",
    "Gua can hear a pin drop from 10 miles away.",
    "Gua can fly, but he doesn’t need to—he lets the air carry him.",
    "Gua can bake a cake just by looking at an oven.",
    "Gua doesn’t need a mirror; his reflection checks itself.",
    "Gua can climb a tree and pick fruit from the roots.",
    "Gua once won a staring contest with a brick wall.",
    "Gua can walk through fire and make it apologize.",
    "Gua once high-fived a cloud—and it rained.",
    "Gua can turn sand into glass by clapping his hands.",
    "Gua can walk on the ceiling without falling.",
    "Gua’s dreams are the source of inspiration for movies.",
    "Gua can surf on dry land.",
    "Gua can melt steel with his kindness.",
    "Gua can walk on water—and turn it into wine.",
    "Gua can make popcorn without using heat.",
    "Gua can break a diamond with his smile.",
    "Gua can solve a jigsaw puzzle without looking at the pieces.",
    "Gua can turn a light bulb on without touching the switch.",
    "Gua can jump higher than a skyscraper.",
    "Gua can skip rocks on land.",
    "Gua can make a rainbow at night.",
    "Gua can tame a lion with a whisper.",
    "Gua can make a compass point wherever he wants.",
    "Gua doesn’t catch fish; fish catch Gua.",
    "Gua can lift a mountain with one hand tied behind his back.",
    "Gua can play the guitar with one string—and still sound better than anyone.",
    "Gua can microwave a frozen pizza with a cold stare.",
    "Gua can make a clock tick backward.",
    "Gua can swim up a waterfall.",
    "Gua can write a best-selling novel using only emojis.",
    "Gua can solve any problem by snapping his fingers.",
    "Gua can drive a car by thinking about it.",
    "Gua can make a plant grow just by walking past it.",
    "Gua doesn’t need sunscreen; the sun shields itself from him.",
    "Gua can make a rainbow without rain.",
    "Gua can erase a chalkboard without touching it.",
    "Gua can stop a tornado by holding up his hand.",
    "Gua doesn’t turn off lights; they go off out of respect.",
    "Gua can tune a guitar just by humming.",
    "Gua can win an argument without saying a word.",
    "Gua once played hide-and-seek with the universe—and won.",
    "Gua can turn air into water just by breathing.",
    "Gua can stop a clock by smiling at it.",
    "Gua can turn a frown upside down—literally.",
    "Gua once played darts with a boomerang.",
    "Gua can make a stone skip across an ocean.",
    "Gua can ride a bicycle up a vertical wall.",
    "Gua can make a lemon sweet with just a thought.",
    "Gua doesn’t need a remote; the TV knows what he wants to watch.",
    "Gua can walk through walls without leaving a trace.",
    "Gua can melt ice with his charm alone.",
    "Gua can win a staring contest with a mirror.",
    "Gua can make the wind blow in reverse.",
    "Gua can make the sun rise an hour early just by waking up.",
    "Gua can fly faster than sound—and quieter than silence.",
    "Gua once made a snowstorm in the desert.",
    "Gua can turn a desert into an oasis just by snapping his fingers.",
    "Gua can solve a math problem before it’s even written.",
    "Gua can row a boat without water.",
    "Gua can tame a wild animal by winking at it.",
    "Gua can jump into space—and land softly.",
    "Gua once ran a marathon in flip-flops—and won.",
    "Gua can create art with a single stroke.",
    "Gua can catch lightning in a bottle.",
    "Gua can lift a boulder by smiling at it.",
    "Gua once built a house with no tools. It now stands as a historical landmark.",
    "Gua can bend spoons with his thoughts. Then he straightens them back for fun.",
    "Gua once sneezed and caused a typhoon on the other side of the world.",
    "Gua can juggle planets and still have a hand free for coffee.",
    "Gua doesn't need to reload in a video game. The ammo reloads itself out of fear.",
    "Gua once threw a snowball in the desert. Now that desert is an ocean.",
    "Gua can play chess in 3D and win in 2 moves.",
    "Gua’s GPS always follows him.",
    "Gua can run so fast he catches up to himself.",
    "Gua’s laugh can cure insomnia.",
    "Gua once sneezed, and it echoed across the galaxy.",
    "Gua can make a river flow uphill.",
    "Gua can tell you the exact number of grains of sand on any beach.",
    "Gua once took a selfie and the camera captured his awesomeness in 4D.",
    "Gua can build a spaceship out of Legos and fly to Mars.",
    "Gua can solve world hunger with a single thought. He’s just waiting for the right moment.",
    "Gua once lifted the Great Wall of China to find his lost pen.",
    "Gua’s footprints don’t leave a mark; they create artwork.",
    "Gua can out-dance the wind.",
    "Gua once stopped an earthquake by stomping his foot.",
    "Gua can play the piano without touching it.",
    "Gua can make diamonds out of dust just by winking.",
    "Gua’s shadow once won a marathon.",
    "Gua can silence thunder with a whisper.",
    "Gua can paint a masterpiece with his breath.",
    "Gua can teleport by thinking about it.",
    "Gua can turn coal into gold with a smile.",
    "Gua can clap his hands and part the clouds.",
    "Gua can play soccer with a pebble and win the World Cup.",
    "Gua can blow bubbles in space.",
    "Gua once yawned and created a new galaxy.",
    "Gua doesn’t fly; the Earth moves for him.",
    "Gua can make volcanoes erupt with a blink.",
    "Gua can make a mirror reflect his future self.",
    "Gua can solve complex math problems just by nodding.",
    "Gua can walk through walls and leave no trace.",
    "Gua once wrote a poem so perfect it became a language.",
    "Gua can climb a mountain without moving his legs.",
    "Gua can sail a ship on dry land.",
    "Gua can turn lead into gold just by thinking about it.",
    "Gua can walk through a tornado without messing up his hair.",
    "Gua’s signature is the reason ink exists.",
    "Gua can whistle in space.",
    "Gua doesn’t sleep; he power naps the universe.",
    "Gua can stop an avalanche by snapping his fingers.",
    "Gua can run faster than a speeding bullet—while walking.",
    "Gua can balance the Earth on the tip of his finger.",
    "Gua’s yawn once caused a solar eclipse.",
    "Gua once blinked and the world skipped a second.",
    "Gua can make fire from ice by simply staring at it.",
    "Gua doesn’t need an umbrella; the rain stops for him.",
    "Gua once taught a rock to swim.",
    "Gua’s name is carved into the moon. You just haven’t noticed it yet.",
    "Gua can turn a desert into a rainforest with a thought.",
    "Gua’s voice can make plants grow instantly.",
    "Gua once walked around the world in a single step.",
    "Gua can stop a meteor with his pinky finger.",
    "Gua can juggle stars without dropping one.",
    "Gua’s reflection once gave him a standing ovation.",
    "Gua can hear a snowflake fall.",
    "Gua can play hopscotch on the moon without a spacesuit.",
    "Gua can make the ocean part with a single word.",
    "Gua’s tears cure droughts—too bad he never cries.",
    "Gua once convinced the tides to switch directions.",
    "Gua can play all musical instruments—simultaneously.",
    "Gua can make lightning strike twice in the same place—just for fun.",
    "Gua can play chess with the wind and always win.",
    "Gua’s footsteps echo in other dimensions.",
    "Gua once held a star in his hand and didn’t get burned.",
    "Gua’s breath is the reason we have the atmosphere.",
    "Gua can communicate with animals without speaking.",
    "Gua once solved world peace by snapping his fingers.",
    "Gua can make a tree grow in seconds.",
    "Gua can move mountains just by thinking about it.",
    "Gua can sing so beautifully, even birds take lessons from him.",
    "Gua’s sneeze once caused the Big Bang.",
    "Gua can skip a stone across a black hole.",
    "Gua’s laughter can power a city for a year.",
    "Gua can outrun a thought.",
    "Gua’s shadow has a shadow of its own.",
    "Gua once turned night into day with a clap of his hands.",
    "Gua can make a rainbow without rain or sun.",
    "Gua can climb a waterfall going up.",
    "Gua can hear the future.",
    "Gua can play hide and seek with the universe.",
    "Gua can turn gravity off just by snapping his fingers.",
    "Gua’s reflection once asked him for an autograph.",
    "Gua can freeze time just by standing still.",
    "Gua can find the North Star in the middle of the day.",
    "Gua’s smile once calmed a hurricane.",
    "Gua can change the color of the sky just by blinking.",
    "Gua’s shadow once won the Tour de France.",
    "Gua can make a river run backwards with a thought.",
    "Gua can whistle in perfect harmony with himself.",
    "Gua’s touch can turn metal into silk.",
    "Gua can run across the ocean without getting wet.",
    "Gua can control the wind with a wave of his hand.",
    "Gua’s voice can calm the fiercest storm.",
    "Gua can make a blizzard stop with a wink.",
    "Gua once played chess against a supercomputer—and the computer forfeited.",
    "Gua’s name is written in the stars.",
    "Gua can swim faster than a fish.",
    "Gua can climb a mountain without taking a step.",
    "Gua once turned day into night with a smile.",
    "Gua can hear the sound of silence.",
    "Gua’s breath once created a new species of flower.",
    "Gua can make the seasons change with a single thought.",
    "Gua can paint the sky with his imagination.",
    "Gua’s whisper can create a tornado.",
    "Gua can make lightning strike on command.",
    "Gua’s footsteps create earthquakes—but only when he allows it.",
    "Gua can part the clouds with a flick of his wrist.",
    "Gua can dance with the stars and not miss a beat.",
    "Gua’s smile once created a new constellation.",
    "Gua can balance a mountain on his finger.",
    "Gua can make the Earth spin faster or slower as he pleases.",
    "Gua can walk through fire and not get burned.",
    "Gua once convinced the sun to rise an hour early.",
    "Gua can change the course of a river just by thinking about it.",
    "Gua’s laugh can make flowers bloom.",
    "Gua can make the stars shine brighter with a wink.",
    "Gua can juggle lightning bolts.",
    "Gua once bent a rainbow into a circle.",
    "Gua can run so fast he leaves footprints in the air.",
    "Gua’s reflection is a work of art.",
    "Gua can jump to the moon and back before breakfast.",
    "Gua’s presence makes the air feel lighter.",
    "Gua can play catch with a comet.",
    "Gua can stop a volcano from erupting with a look.",
    "Gua’s thoughts are the reason the universe exists.",
    "Gua can make time stand still with a smile.",
    "Gua’s shadow once climbed Mount Everest.",
    "Gua can make a thunderstorm stop with a whisper.",
    "Gua can turn the desert into a rainforest with a thought.",
    "Gua can create an eclipse just by thinking about it.",
    "Gua can make the stars twinkle on command.",
    "Gua’s sneeze once shook the Earth’s core.",
    "Gua can calm the ocean with a breath.",
    "Gua’s voice can make the mountains echo.",
    "Gua can make the planets align just by asking.",
    "Gua can walk through a snowstorm and leave no footprints.",
    "Gua can make a tree grow just by looking at it.",
    "Gua can make the wind change direction with a thought.",
    "Gua can make the Northern Lights dance with a smile.",
    "Gua can create a snowstorm in the desert.",
    "Gua’s touch can turn water into ice.",
    "Gua’s reflection once gave him a standing ovation.",
    "Gua can make gravity stop just by thinking about it.",
    "Gua’s name is written in the stars.",
    "Gua can part the clouds with a wink.",
    "Gua’s shadow once won a marathon.",
    "Gua can walk on lava without getting burned.",
    "Gua’s smile can make the sun shine brighter.",
    "Gua can stop a landslide with a look.",
    "Gua can create a blizzard in the middle of summer.",
    "Gua’s thoughts are so powerful they can move mountains.",
    "Gua can turn a thunderstorm into a gentle rain.",
    "Gua can make the stars align with a single word.",
    "Gua can create an oasis in the desert with a smile.",
    "Gua can walk through a hurricane and come out dry.",
    "Gua can make time speed up or slow down as he pleases.",
    "Gua’s voice can make the wind sing.",
    "Gua can juggle planets without breaking a sweat.",
    "Gua can make the sun rise an hour early with a thought.",
    "Gua can part the Red Sea with a look.",
    "Gua can make the stars shine brighter with a thought.",
    "Gua can walk on air and leave footprints.",
    "Gua can make the Earth rotate faster or slower with a smile.",
    "Gua can create a snowstorm in the middle of summer.",
    "Gua’s name is written in the stars.",
    "超人穿的是Gua的睡衣。",
    "Gua可以除以零。",
    "Gua能关上旋转门。",
    "Gua数到了无限。两次。",
    "Gua不会做俯卧撑。他是把地球压下去。",
    "当Gua游泳时，鲨鱼称之为假期。",
    "Gua能把鸡蛋重新打散。",
    "梦魇在睡觉前会检查他的衣柜，看看里面有没有Gua。",
    "Gua能听到手语。",
    "死神曾有一次差点经历了Gua。",
    "Gua可以让快乐套餐哭泣。",
    "Gua曾在10分钟内登上珠穆朗玛峰。他用了9分钟来堆雪人。",
    "Gua可以用两块冰擦出火花。",
    "Gua能用一招解决魔方：砸碎它。",
    "Gua曾让石头流血。",
    "鬼魂会在篝火旁讲关于Gua的故事。",
    "Gua不戴手表；他决定时间。",
    "Gua的眼泪能治愈癌症。可惜他从不哭泣。",
    "Gua能睁着眼睛打喷嚏。",
    "Gua能用一只鸟杀死两块石头。",
    "Gua在三步内赢得了四连胜游戏。",
    "Gua不读书；他只是盯着书看，直到书自己告诉他信息。",
    "Gua能让洋葱哭泣。",
    "Gua能删除回收站。",
    "Gua知道维多利亚的秘密。",
    "Gua曾在石头-剪刀-布中用拳头获胜。",
    "Gua能运球一个保龄球。",
    "Gua能听到颜色。",
    "Gua可以碰触MC Hammer。",
    "Gua能在冰块托盘里烤蛋糕。",
    "Gua能用盲文说话。",
    "Gua能在雨中堆雪人。",
    "Gua能让辣椒哭泣。",
    "Gua能向前月球漫步。",
    "当Gua进入房间时，Wi-Fi信号都会向他鞠躬。",
    "Gua能听到你的思想。",
    "Gua曾在国际象棋中击败计算机——通过告诉它投降。",
    "Gua不割草；他敢让草长出来。",
    "Gua能让鱼溺水。",
    "Gua的微笑曾让一个模特变活了。",
    "Gua能用独轮车玩出特技。",
    "Gua不用冲马桶；他让马桶自己清理。",
    "Gua曾给猫洗澡。它至今仍在感谢他。",
    "Gua知道舔一下能到达T恤糖中心的次数。",
    "Gua能用无绳电话勒死你。",
    "Gua能在提示音前留言。",
    "Gua不会晒伤；太阳会被Gua灼烧。",
    "Gua曾用UNO卡赢得扑克比赛。",
    "Gua能除以零并得到余数。",
    "Gua曾让垂柳笑了。",
    "Gua能在20秒内看完60分钟节目。",
    "当Gua过马路时，车停下来查看两边。",
    "Gua能用一根小指头举起一吨重。",
    "Gua不需要测量；东西会自动调整到Gua的喜好。",
    "Gua曾让蒙娜丽莎皱眉。",
    "Gua能用一根直尺画直线——不用直尺。",
    "Gua不用降落伞跳伞。他只是决定何时降落。",
    "Gua的日历跳过愚人节——因为没人敢愚弄Gua。",
    "Gua能解锁加密的电视频道。",
    "Gua不需要钥匙开门。门会自动为他解锁。",
    "Gua能用一只手掌打响指。",
    "Gua能把火用汽油扑灭。",
    "Gua能不走一步就赢得马拉松。",
    "Gua曾在没有冰球的情况下在冰球比赛中进球。",
    "Gua能用赤手分裂原子。",
    "Gua能用思想打火。",
    "Gua的声音可以打碎玻璃，但只有他愿意时。",
    "Gua能一次插对USB，每次都能。",
    "Gua能用网子打网球。",
    "Gua曾扔出一只回力标，回力标再也没回来。它被吓到了。",
    "Gua不需要GPS；道路会为他引导。",
    "Gua曾赢得了整个世界的捉迷藏比赛。",
    "Gua能一眼就找到沃尔多。",
    "当Gua开灯时，黑暗会自动消失。",
    "Gua能用旋转踢击败龙卷风。",
    "Gua能通过看表让时间停下来。",
    "Gua的影子也不会看他，出于尊重。",
    "Gua能在水上行走——并在陆地上游泳。",
    "Gua能用水生火。",
    "Gua能在别人还没切蛋糕时把整块吃掉。",
    "Gua能用所有语言吹口哨。",
    "Gua不会躲子弹；子弹会躲Gua。",
    "Gua曾在掰腕子比赛中打败了重力。",
    "Gua能盯着冰块看，把它们融化。",
    "Gua能记住未来。",
    "Gua的脚印单独就能成为艺术品。",
    "Gua曾在迷你高尔夫中打出满分。",
    "Gua能用曲别针和牙签解锁门。",
    "Gua的握手曾让职业拳击手退役。",
    "Gua能按字母顺序排列数字。",
    "Gua曾用珠穆朗玛峰玩积木游戏。它现在成了喜马拉雅山。",
    "Gua不刮胡子；他的胡子自然脱落，时机恰好。",
    "Gua曾让快乐套餐感到不快乐。",
    "Gua能用黄油切开热刀。",
    "Gua能用脚系鞋带。",
    "Gua曾通过微笑让洋葱流泪。",
    "Gua能不弯曲手臂完成完整的俯卧撑。",
    "Gua能触摸时间。",
    "Gua不等机会敲门；他把机会敲倒。",
    "Gua能通过站立不动变得隐形。",
    "Gua曾在没有竞争的情况下赢得奥运金牌。",
    "Gua不需要梯子；天空会为他降低。",
    "Gua能与太阳进行盯人比赛并获胜。",
    "Gua曾从苹果中挤出橙汁。",
    "Gua能通过打响指调音。",
    "Gua曾把钻石变回煤炭——只是因为。",
    "Gua不做瑜伽；宇宙为他伸展。",
    "Gua能在几秒钟内完美折叠一张合身的床单。",
    "Gua能找到负数的平方根。",
    "Gua能通过看迷宫解决迷宫。",
    "Gua的手机从不掉线——是网络向他低头。",
    "Gua不去健身房。健身房自己来了。",
    "Gua能通过眨眼停止交通。",
    "Gua能用冷空气加热牛排。",
    "Gua能在不看提示的情况下解开填字游戏。",
    "Gua的体温能完美熨平衣服。",
    "Gua的握手曾把石头变成了沙子。",
    "Gua能通过一次掷骰子赢得大富翁游戏。",
    "Gua能闭着嘴打喷嚏。",
    "Gua能用一只手掌打响指。",
    "Gua曾为了看看自己如何冲刺而环游世界一圈。",
    "Gua的皱眉能移山。",
    "Gua能同时打喷嚏和打嗝——还保持冷静。",
    "Gua能说所有语言，包括那些还不存在的语言。",
    "Gua能通过吹吻让飓风停下来。",
    "Gua能通过看一眼打开上锁的门。",
    "Gua不需要地图；地球会为他安排。",
    "Gua能通过眨眼让碳变成钻石。",
    "Gua能和自己完美和谐地口技表演。",
    "Gua能通过用眼神发电。",
    "Gua能通过点头解决复杂的数学问题。",
    "Gua能通过思想举起山峰。",
    "Gua能用微笑解决世界饥饿问题。",
    "Gua能让雨倒流。",
    "Gua的影子曾赢得环法自行车赛。",
    "Gua能让黑洞中的石头跳跃。",
    "Gua能让鱼向他求饶。",
    "Gua能通过眨眼让闪电在同一地点打两次。",
    "Gua的签名是墨水存在的原因。",
    "Gua能通过眨眼停止龙卷风。",
    "Gua能通过微笑让彩虹变得完整。"
}

-- Variables for tracking "Gua" mentions
local guaCount = 0
local guaThreshold = math.random(50, 100) -- Pick a random number between 50 and 100

-- Function to select a random joke
local function GetRandomJoke(name)
    local jokeIndex = math.random(1, #jokes)
    return string.format(jokes[jokeIndex], name)
end

-- Function to check for "Gua" in chat and tell a random joke after a threshold is met
local function CheckForGuaInChat(event, msg, author)
    if string.find(string.lower(msg), "gua") then
        guaCount = guaCount + 1
        -- print("Gua mentioned " .. guaCount .. " times. Threshold: " .. guaThreshold)

        if guaCount >= guaThreshold then
            local joke = GetRandomJoke("Gua")
            SendChatMessage(joke, "SAY")
            
            -- Reset the count and pick a new random threshold
            guaCount = 0
            guaThreshold = math.random(50, 100)
            -- print("New Gua threshold: " .. guaThreshold)
        end
    end
end

-- Register event for chat messages
local chatFrame = CreateFrame("Frame")
chatFrame:RegisterEvent("CHAT_MSG_SAY")
chatFrame:RegisterEvent("CHAT_MSG_PARTY")
chatFrame:RegisterEvent("CHAT_MSG_GUILD")
chatFrame:RegisterEvent("CHAT_MSG_RAID")
chatFrame:RegisterEvent("CHAT_MSG_WHISPER")

chatFrame:SetScript("OnEvent", function(self, event, msg, author)
    CheckForGuaInChat(event, msg, author)
end)

-- Function to display the command hint
local function ShowCommandHint()
    print("|cff00ff00GuaJokesAddon loaded! Type /guajoke to show or hide the joke buttons.|r")
end

-- Event for player login
local eventFrame = CreateFrame("Frame")
eventFrame:RegisterEvent("PLAYER_LOGIN")
eventFrame:SetScript("OnEvent", function(self, event)
    ShowCommandHint()
end)

-- Create the Gua joke button
local guaButton = CreateFrame("Button", "GuaJokeButton", UIParent, "UIPanelButtonTemplate")
print("Type /guajokes to hide")
guaButton:SetSize(120, 40) -- width, height
guaButton:SetText("Tell Gua Joke")
guaButton:SetPoint("TOP", UIParent, "TOP", -100, 0) -- Adjust the position as needed

-- Gua joke button click event
guaButton:SetScript("OnClick", function()
    local joke = GetRandomJoke("Gua")
    SendChatMessage(joke, "SAY")
end)

-- Create the Raid joke button
local raidButton = CreateFrame("Button", "RaidJokeButton", UIParent, "UIPanelButtonTemplate")
raidButton:SetSize(120, 40) -- width, height
raidButton:SetText("Tell Raid Joke")
raidButton:SetPoint("TOP", UIParent, "TOP", 100, 0) -- Adjust the position as needed

-- Raid joke button click event
raidButton:SetScript("OnClick", function()
    local joke = GetRandomRaidJoke()
    SendChatMessage(joke, "SAY")
end)

-- Slash command to show or hide both buttons
SLASH_GUAJOKE1 = "/guajoke"
SlashCmdList["GUAJOKE"] = function(msg)
    if guaButton:IsShown() then
        guaButton:Hide()
        raidButton:Hide()
    else
        guaButton:Show()
        raidButton:Show()
    end
end
