local jokes = {
-- General Chuck Norris-style jokes
  "%s doesn't read books. He stares them down until they give up their information.",
  "%s counted to infinity... twice.",
  "When the Boogeyman goes to sleep every night, he checks his closet for %s.",
  "%s can divide by zero.",
  "%s can slam a revolving door.",
  "%s's tears cure cancer. Too bad %s has never cried.",
  "%s once kicked a horse in the chin. Its descendants are known today as giraffes.",
  "%s doesn't wear a watch. He decides what time it is.",
  "%s can hear sign language.",
  "Death once had a near-%s experience.",
  "%s makes onions cry.",
  "%s can strangle you with a cordless phone.",
  "%s once won a game of Connect Four in three moves.",
  "%s can kill two stones with one bird.",
  "%s doesn't mow his lawn. He dares it to grow.",
  "The flu gets a %s shot every year.",
  "%s beat the sun in a staring contest.",
  "%s can dribble a bowling ball.",
  "%s's calendar goes straight from March 31st to April 2nd. No one fools %s.",
  "%s can speak braille.",
  "%s's house has no doors, only walls that he walks through.",
  "%s once got bit by a cobra. After five days of excruciating pain, the cobra died.",
  "%s doesn't dial the wrong number. You pick up the wrong phone.",
  "%s can sneeze with his eyes open.",
  "%s's blood type is AK-47.",
  "%s once won a staring contest with his own reflection.",
  "When %s does push-ups, he isn't lifting himself up; he's pushing the Earth down.",
  "%s can light a fire by rubbing two ice cubes together.",
  "%s's dog picks up his own poop because %s doesn't take crap from anyone.",
  "%s's computer doesn't have a 'backspace' key because %s doesn't make mistakes.",
  "%s once ordered a steak in a vegan restaurant—and got it.",
  "%s can do a wheelie on a unicycle.",
  "%s doesn't need a keyboard to press Ctrl+Alt+Delete.",
  "%s once scared a hurricane into staying out at sea.",
  "%s's shadow has never been seen.",
  "%s can build a snowman out of rain.",
  "%s once won the World Series of Poker using UNO cards.",
  "%s can grill a popsicle.",
  "%s's sweat is the cure for the common cold.",
  "%s doesn't flush the toilet; he scares the crap out of it.",
  "%s once punched a cyclops between the eye.",
  "%s can drown a fish.",
  "%s once had a heart attack; his heart lost.",
  "%s can unscramble an egg.",
  "%s knows Victoria's secret.",
  "%s's smile once brought a puppy back to life.",
  "%s can gargle peanut butter.",
  "%s once won a race against light.",
  "%s can make a slinky go upstairs.",
  "%s's handshake is the equivalent of a lightning strike.",
  "%s once won a staring contest with the sun.",
  "%s can pick oranges from an apple tree and make the best lemonade you've ever tasted.",
  "%s once kicked the Earth and it hasn't stopped spinning since.",
  "%s can clap with one hand.",
  "%s doesn't get sunburned; the sun gets %s-burned.",
  "%s can hear colors and see sounds.",
  "When %s was born, he drove his mom home from the hospital.",
  "%s can make a snowball out of rain.",
  "%s doesn't need to sleep; sleep needs %s.",
  "%s can start a fire with a magnifying glass—at night.",
  "%s once beat the moon in a staring contest.",
  "%s can squeeze orange juice out of a lemon.",
  "%s's reflection looks away out of fear.",
  "%s doesn't breathe; he holds air hostage.",
  "%s can tie his shoes with his feet.",
  "%s doesn't need a parachute; the ground comes up to meet him softly.",
  "%s can unscramble scrambled eggs.",
  "%s's stare can cure the blind.",
  "%s can kill time without injuring eternity.",
  "%s once challenged his own shadow to a fight. It lost.",
  "%s can hear a pin drop from miles away.",
  "%s doesn't wear shoes; the earth protects his feet.",
  "%s can touch MC Hammer.",
  "%s's watch runs on his own time.",
  "%s once won a marathon without running.",
  "%s doesn't need a GPS; he decides where he is.",
  "%s's sneeze once caused a hurricane.",
  "%s can strum a guitar without strings.",
  "%s can lift a mountain with one hand.",
  "%s can fold paper more than seven times.",
  "%s's jokes are so funny, even the stones laugh.",
  "%s doesn't catch colds; colds catch %s.",
  "%s's signature requires no ink.",
  "%s once turned a vampire into a vegetarian.",
  "%s can win a game of chess in one move.",
  "%s can solve a Rubik's Cube with one hand tied behind his back.",
  "%s doesn't age; time gets old waiting for %s.",
  "%s once built a snowman out of rain.",
  "%s can whistle in all languages.",
  "%s once got pulled over for speeding, but let the cop go with a warning.",
  "%s can count to infinity backward.",
  "%s can delete the Recycling Bin.",
  "%s's laugh can heal the sick.",
  "%s doesn't need to read; words assemble themselves in his mind.",
  "%s can set ants on fire with a magnifying glass. At night.",
  "%s once won a game of rock-paper-scissors using only rock.",
  "%s can split an atom with his bare hands.",
  "%s doesn't need a phone; he communicates telepathically.",
  "%s can roundhouse kick faster than the speed of light.",
  "%s's smile once brought a unicorn back to life.",
  "%s can make a cake without ingredients.",
  "%s can touch this.",
  "%s can jump-start a car by staring at it.",
  "%s doesn't swim; water moves around him.",
  "%s can bake cookies in a freezer.",
  "%s once punched a hole through a brick wall. Without using his hands.",
  "%s can program a computer without a keyboard.",
  "%s doesn't get frostbite; frost gets %s-bite.",
  "%s can watch an entire season of a TV show in one second.",
  "%s once climbed Mount Everest in shorts and flip-flops.",
  "%s's mind is the cloud.",
  "%s doesn't get brain freeze; even ice is afraid to hurt %s.",
  "%s can squeeze water from a rock.",
  "%s can light up a room just by walking in.",
  "%s doesn't need to shave; his beard is afraid to grow.",
  "%s once taught a German Shepherd to bark in Spanish.",
  "%s can strum a piano.",
  "%s can read minds. He just chooses not to.",
  "%s doesn't need a shower; dirt is afraid to touch him.",
  "%s can win at solitaire with only one card.",
  "%s can fold origami with his eyes closed.",
  "%s can sit in the corner of a round room.",
  "%s once won a staring contest with Medusa.",
  "%s can make a rainbow with a monochrome camera.",
  "%s doesn't need to read maps; maps follow %s.",
  "%s can do a wheelie on a stationary bike.",
  "%s doesn't need a parachute; gravity respects him.",
  "%s can unscramble letters before they're scrambled.",
  "%s's jokes make comedians laugh.",
  "%s can make the wind change direction.",
  "%s doesn't need tools; materials assemble themselves for him.",
  "%s can finish a book by looking at the cover.",
  "%s can answer rhetorical questions.",
  "%s's thoughts can power a city.",
  "%s can beat the house in solitaire.",
  "%s's breath can turn coal into diamonds.",
  "%s doesn't need to warm up; he's always ready.",
  "%s can paint a masterpiece with a single brushstroke.",
  "%s can make the impossible possible.",
  "%s doesn't need to ask for directions; directions ask for him.",
  "%s can read the future.",
  "%s can stand at the edge of an endless ocean.",
  "%s can taste lies.",
  "%s can balance the unbalanced.",
  "%s can sleep with his eyes open.",
  "%s can make flowers bloom by looking at them.",
  "%s doesn't need a key; doors open themselves for him.",
  "%s can walk through walls.",
  "%s can make a statue move.",
  "%s can see in the dark.",
  "%s can write an unwritten law.",
  "%s can make the Earth stop spinning.",
  "%s can turn water into ice by staring at it.",
  "%s can be in two places at once.",
  "%s can see through solid objects.",
  "%s can make a mirror reflect its own image.",
  "%s can play all musical instruments at once.",
  "%s can find the beginning of a circle.",
  "%s can make the sun rise in the west.",
  "%s can breathe in space.",
  "%s can make a rainbow with a garden hose.",
  "%s can make time go backward.",
  "%s can open a door that doesn't exist.",
  "%s can make a rock float.",
  "%s can jump to the moon.",
  "%s can silence thunder.",
  "%s can make gravity stop working.",
  "%s can walk on clouds.",
  "%s can see the wind.",
  "%s can make a wish come true.",
  "%s can hold his breath indefinitely.",
  "%s can make the impossible happen.",
  "%s can see the end of infinity.",
  "%s can stand on the edge of nothing.",
  "%s can make the sun shine at night.",
  "%s can turn darkness into light.",
  "%s can find the smallest particle.",
  "%s can hear the heartbeat of the universe.",
  "%s can split the ocean.",
  "%s can make mountains bow.",
  "%s can count the stars.",
  "%s can catch lightning in a bottle.",
  "%s can make the Earth smile.",
  "%s can touch a star.",
  "%s can command the elements.",
  "%s can stop a volcano from erupting.",
  "%s can calm a storm with a whisper.",
  "%s can turn night into day.",
  "%s can hold the universe in his hand.",
  "%s can make the desert bloom.",
  "%s can make the seas part.",
  "%s can make the Earth stand still.",
  "%s can create life with a thought.",
  "%s can speak every language.",
  "%s can hear the sound of a butterfly's wings.",
  "%s can turn lead into gold.",
  "%s can change the course of history.",
  "%s can make the blind see.",
  "%s can make the lame walk.",
  "%s can turn water into wine.",
  "%s can heal with a touch.",
  "%s can make the dead rise.",
  "%s can ascend without leaving the ground.",
  "%s can create something out of nothing.",
  "%s can make the deaf hear.",
  "%s can see the unseen.",
  "%s can touch the untouchable.",
  "%s can know the unknowable.",
  "%s can find what was never lost.",
  "%s can climb the highest mountain without moving.",
  "%s can cross the widest ocean without swimming.",
  "%s can reach the unreachable star.",
  "%s can solve the unsolvable riddle.",
  "%s can answer the unanswerable question.",
  "%s can break the unbreakable.",
  "%s can tame the wildest beast.",
  "%s can find the end of space.",
  "%s can swim in solid ground.",
  "%s can see the other side of a black hole.",
  "%s can make a sound in the vacuum of space.",
  "%s can find the square root of a negative number.",
  "%s can make two plus two equal five.",
  "%s can stop time.",
  "%s can travel faster than light.",
  "%s can exist in multiple dimensions.",
  "%s can communicate with all living things.",
  "%s can be everywhere at once.",
  "%s can create a perfect circle freehand.",
  "%s can write an endless story.",
  "%s can build a bridge across the sky.",
  "%s can drink from an empty cup.",
  "%s can find the last digit of pi.",
  "%s can solve a problem before it exists.",
  "%s can jump over his own shadow.",
  "%s can turn dreams into reality.",
  "%s can open doors that are closed.",
  "%s can close doors that are open.",
  "%s can touch music.",
  "%s can see thoughts.",
  "%s can taste colors.",
  "%s can smell emotions.",
  "%s can feel time.",
  "%s can balance the universe.",
  "%s can change his destiny.",
  "%s can make a stone bleed.",
  "%s can break unbreakable bonds.",
  "%s can end infinity.",
  "%s can make the sky fall.",
  "%s can split the sea.",
  "%s can make the Earth quake.",
  "%s can silence the world.",
  "%s can create new elements.",
  "%s can see the future.",
  "%s can remember the future.",
  "%s can forget the past.",
  "%s can erase memories.",
  "%s can read a closed book.",
  "%s can write in the air.",
  "%s can hear the silence.",
  "%s can see the darkness.",
  "%s can touch the void.",
  "%s can move the immovable.",
  "%s can know the unknown.",
  "%s can break the sound barrier with a whisper.",
  "%s can make a blind man see.",
  "%s can make a mute man speak.",
  "%s can make a deaf man hear.",
  "%s can make stones sing.",
  "%s can make trees dance.",
  "%s can make rivers flow uphill.",
  "%s can turn back the hands of time.",
  "%s can leap tall buildings in a single bound.",
  "%s can change the color of the sky.",
  "%s can outsmart himself.",
  "%s can create a square circle.",
  "%s can measure the immeasurable.",
  "%s can make the finite infinite.",
  "%s can find the center of the universe.",
  "%s can define the undefined.",
  "%s can explain the inexplicable.",
  "%s can calculate the incalculable.",
  "%s can foresee the unforeseeable.",
  "%s can dream the undreamable.",
  "%s can create a new primary color.",
  "%s can capture the wind.",
  "%s can see sound waves.",
  "%s can feel the rotation of the Earth.",
  "%s can walk through fire unharmed.",
  "%s can bend light.",
  "%s can create a new dimension.",
  "%s can hold the weight of the world.",
  "%s can count the grains of sand on a beach.",
  "%s can see the edge of the universe.",
  "%s can answer any question.",
  "%s can solve any problem.",
  "%s can be in two places at once.",
  "%s can live forever.",
  "%s can know everything.",
  "%s can see the past, present, and future all at once.",
  "%s can make one plus one equal three.",
  "%s can make the sun rise at midnight.",
  "%s can turn glass back into sand.",
  "%s can make rain fall upward.",
  "%s can make the tides stop.",
  "%s can create life.",
  "%s can end life.",
  "%s can make a stone float.",
  "%s can make the sky green and the grass blue.",
  "%s can make the clouds take shape.",
  "%s can hold the moon in his hand.",
  "%s can make stars fall from the sky.",
  "%s can walk on water.",
  "%s can touch the horizon.",
  "%s can control the weather.",
  "%s can make the Earth spin backward.",
  "%s can see through time.",
  "%s can make colors invisible.",
  "%s can read the mind of a rock.",
  "%s can silence an echo.",
  "%s can divide by zero.",
  "%s can make a mirror reflect its own image.",
  "%s can play a silent song.",
  "%s can freeze fire.",
  "%s can boil ice.",
  "%s can make a circle have corners.",
  "%s can make a straight line curve.",
  "%s can find the end of a rainbow.",
  "%s can count the drops in the ocean.",
  "%s can live without existing.",
  "%s can exist without living.",
  "%s can see the sound of silence.",
  "%s can taste the color blue.",
  "%s can smell the number nine.",
  "%s can touch a thought.",
  "%s can hear the light.",
  "%s can make the mountains bow.",
  "%s can stop a bullet with a glance.",
  "%s can make a river flow backward.",
  "%s can find the lost city of Atlantis.",
  "%s can tame a tornado.",
  "%s can make stones float.",
  "%s can stop an earthquake.",
  "%s can hold fire in his hands.",
  "%s can make shadows flee.",
  "%s can make the sun stand still.",
  "%s can make the moon shine during the day.",
  "%s can make the stars dance.",
  "%s can climb a bottomless pit.",
  "%s can play a violin with a drumstick.",
  "%s can make a whisper echo.",
  "%s can see the wind.",
  "%s can touch the sky.",
  "%s can make silence louder.",
  "%s can make darkness visible.",
  "%s can find the last page of the internet.",
  "%s can solve the mystery of the Bermuda Triangle.",
  "%s can find the smallest number.",
  "%s can lift the heaviest weight.",
  "%s can make time wait.",
  "%s can make gravity stop working.",
  "%s can make a mountain out of a molehill.",
  "%s can make a molehill out of a mountain.",
  "%s can see with his eyes closed.",
  "%s can hear with his ears plugged.",
  "%s can taste without eating.",
  "%s can smell without breathing.",
  "%s can feel without touching.",
  "%s can know without learning.",
  "%s can think without thinking.",
  "%s can be and not be at the same time.",
  "%s can turn nothing into something.",
  "%s can reach the unreachable.",
  "%s can conquer the unconquerable.",
  "%s can change the unchangeable.",
  "%s can see the invisible.",
  "%s can touch the intangible.",
  "%s can hear the inaudible.",
  "%s can move the immovable.",
  "%s can stop the unstoppable.",
  "%s can start the unstartable.",
  "%s can break the unbreakable.",
  "%s can bend the unbendable.",
  "%s can know the unknowable.",
  "%s can find the unfound.",
  "%s can solve the unsolvable.",
  "%s can win the unwinnable.",
  "%s can pass the impassable.",
  "%s can climb the unclimbable.",
  "%s can cross the uncrossable.",
  "%s can catch the uncatchable.",
  "%s can capture the uncapturable.",
  "%s can kill the unkillable.",
  "%s can defeat the undefeatable.",
  "%s can create the uncreatable.",
  "%s can imagine the unimaginable.",
  "%s can achieve the unattainable.",
  "%s can explain the unexplainable.",
  "%s can be the unbeatable.",
  "%s can do the impossible.",
  "%s can make the impossible possible.",

  -- World of Warcraft-specific jokes
  "When %s enters a raid, bosses drop their loot and run.",
  "%s doesn't do quests; NPCs just give him experience out of fear.",
  "Deadmines was originally called '%s's Mines' until he allowed the Defias to borrow it.",
  "%s doesn't ride mounts; the ground moves beneath him.",
  "When %s plays a hunter, his pets tame themselves.",
  "The Dark Portal is actually %s's doorbell.",
  "%s doesn't need hearthstones; he decides where home is.",
  "Even the Lich King waits for %s to make the first move.",
  "%s once soloed a raid boss—on a level 1 character.",
  "When %s visits Ironforge, the Great Forge burns hotter out of respect.",
  "%s doesn't need stealth; mobs pretend not to see him.",
  "Thunderfury, Blessed Blade of the Windseeker, once asked %s for an autograph.",
  "Blackrock Mountain was formed when %s had a barbecue.",
  "%s doesn't learn spells; spells learn %s.",
  "When %s enters Battlegrounds, the other faction logs off.",
  "%s once fished up the Loch Ness Monster in Stormwind's canals.",
  "The Titans look up to %s.",
  "%s can cleanse Corrupted Ashbringer.",
  "Murlocs have a statue of %s underwater.",
  "When %s opens a treasure chest, it thanks him.",
  "Dragons tell tales of %s to their young to keep them in line.",
  "%s doesn't need to farm gold; gold farms itself for %s.",
  "The only reason Azeroth hasn't been destroyed is because %s lives there.",
  "%s once crit a critter for over 9,000 damage.",
  "Zones become rest areas when %s enters them.",
  "%s's login screen doesn't have a button; the game starts when %s is ready.",
  "Even Illidan knows %s was prepared.",
  "When %s visits the Barber Shop, the styles change.",
  "%s's minimap shows the entire world.",
  "PvP arenas were originally training grounds to fight %s.",
  "%s can equip mail armor at level 1.",
  "Guilds compete to have %s as a member.",
  "%s doesn't need achievements; achievements need %s.",
  "When %s uses Hearthstone, the innkeeper thanks him for returning.",
  "%s once defeated a boss before the cutscene ended.",
  "Even the Auctioneer gives %s the best prices.",
  "%s can /yawn and put enemies to sleep.",
  "Deathwing had nightmares about %s.",
  "Professions level up when %s thinks about them.",
  "%s doesn't need a user interface; the game plays itself for him.",
  "When %s jumps, gravity pauses out of respect.",
  "%s's pets have pets.",
  "Legendaries drop for %s during daily quests.",
  "Even the loading screen tips listen to %s.",
  "%s doesn't need to roll for loot; the loot rolls to him.",
  "NPCs give %s quests just to spend time with him.",
  "The zone changes music when %s arrives.",
  "%s once healed a wound before it happened.",
  "Spells go off cooldown early for %s.",
  "Raid lockouts reset when %s is ready.",
  "Even ghosts wait for %s's permission to resurrect.",
  "World bosses consider %s their boss.",
  "%s's mail is never late.",
  "Bosses drop mounts for %s every time.",
  "%s can mine herbs and pick ore.",
  "When %s explores a zone, it stays explored.",
  "Even the map asks %s for directions.",
  "%s doesn't need to gather; materials gather themselves for him.",
  "Armor repairs itself for %s.",
  "When %s casts a spell, it never misses.",
  "%s once tamed a beast by staring at it.",
  "Zones become sanctuaries when %s enters.",
  "Even quest items find their way to %s's bags.",
  "%s can activate abilities that are on cooldown.",
  "Mounts increase their speed for %s.",
  "When %s logs in, the server thanks him.",
  "Enemies attack themselves rather than face %s.",
  "%s can dual-wield two-handed weapons in one hand.",
  "Even the login screen bows to %s.",
  "%s's logout timer is instant because the game never wants him to leave.",
  "Battlegrounds end when %s joins.",
  "%s can tank while healing and DPSing.",
  "When %s enters stealth, the shadows hide.",
  "Pets ask %s for abilities.",
  "Even the GMs ask %s for help.",
  "%s doesn't need to eat or drink; he is always at full health and mana.",
  "Flight paths take the route %s decides.",
  "Mounts wait for %s to ride them.",
  "%s can fish without a pole.",
  "Even the Auction House pays %s.",
  "Armor sets adjust to %s's class.",
  "%s's talent points assign themselves.",
  "World events happen on %s's schedule.",
  "Even cross-faction communication is possible with %s.",
  "%s can enter instances without keys or attunements.",
  "Boats and zeppelins wait for %s.",
  "%s can solo group quests without effort.",
  "Even the loading screens load faster for %s.",
  "Critters salute %s when he passes.",
  "%s's name is always reserved on new servers.",
  "Guild banks offer %s unlimited withdrawals.",
  "Even elites become non-hostile around %s.",
  "%s can enchant without materials.",
  "Mail deliveries are instant for %s.",
  "Even the Void Storage has infinite space for %s.",
  "%s's spells don't cost mana.",
  "World buffs seek out %s.",
  "Even the Black Market Auction House gives items to %s for free.",
  "%s's queue times are nonexistent.",
  "Quests auto-complete for %s.",
  "Even timewalking dungeons adjust to %s's level.",
  "%s can transmog any item to any appearance.",
  "Mounts gain new abilities when %s rides them.",
  "Even the in-game clock follows %s's time.",
  "%s can use abilities from any class.",
  "Bank slots are limitless for %s.",
  "Even the hardest achievements unlock themselves for %s.",
  "Guild perks are doubled for %s.",
  "Even the game credits %s as a developer.",
  "%s can pause and rewind the game.",
  "Legendary items seek %s as their wielder.",
  "Even NPCs cheer when %s logs in.",
  "Battle pets level themselves for %s.",
  "%s can trade soulbound items.",
  "Even the weather changes according to %s's mood.",
  "%s can speak all languages.",
  "Guild chat listens when %s speaks.",
  "Bosses drop extra loot for %s.",
  "%s can hearth anywhere without a stone.",
  "Even the login music changes for %s.",
  "%s's achievements are legendary.",
  "Even the game lore mentions %s."
}
-- Assign the jokes table to the global scope
_G.jokes = jokes
