local jokes = {
    "%s once was bitten by a copperhead snake. After 3 days of agonizing pain, the snake died.",
    "Superman wears Chuck Norris pajamas. Chuck Norris wears %s pajamas.",
    "%s can divide by zero.",
    "%s can slam a revolving door.",
    "%s counted to infinity. Twice.",
    "%s doesn’t do push-ups. He pushes the Earth down.",
    "When %s goes swimming, sharks call it a vacation.",
    "%s can unscramble an egg.",
    "The boogeyman checks his closet for %s before going to bed.",
    "%s can hear sign language.",
    "Death once had a near-%s experience.",
    "%s can make a Happy Meal cry.",
    "%s once climbed Mt. Everest in 10 minutes. He spent 9 of those minutes building a snowman.",
    "%s can light a fire by rubbing two ice cubes together.",
    "%s can solve a Rubik’s Cube in one move: smashing it.",
    "%s once made a rock bleed.",
    "Ghosts tell stories about %s around the campfire.",
    "%s doesn’t wear a watch; he decides what time it is.",
    "%s’s tears cure cancer. Too bad he has never cried.",
    "%s can sneeze with his eyes open.",
    "%s can kill two stones with one bird.",
    "%s once won a game of Connect Four in three moves.",
    "%s doesn’t read books; he stares them down until they give him the information.",
    "%s can make onions cry.",
    "%s can delete the recycling bin.",
    "%s knows Victoria’s secret.",
    "%s once won a game of rock-paper-scissors using only his fist.",
    "%s can dribble a bowling ball.",
    "%s can hear colors.",
    "%s can touch MC Hammer.",
    "%s can bake a cake in an ice cube tray.",
    "%s can speak Braille.",
    "%s can build a snowman out of rain.",
    "%s can make a jalapeño cry.",
    "%s can moonwalk forwards.",
    "When %s enters the room, Wi-Fi signals bow to him.",
    "%s can hear your thoughts.",
    "%s once beat a computer at chess—by telling it to give up.",
    "%s doesn’t mow his lawn; he dares the grass to grow.",
    "%s can make a fish drown.",
    "%s’s smile once brought a mannequin to life.",
    "%s can do a wheelie on a unicycle.",
    "%s doesn't flush the toilet; he scares the stuff down.",
    "%s once gave a cat a bath. It still hasn't stopped thanking him.",
    "%s knows how many licks it takes to get to the center of a Tootsie Pop.",
    "%s can strangle you with a cordless phone.",
    "%s can leave a message before the beep.",
    "%s doesn’t get sunburned; the sun gets %s-burned.",
    "%s once won a game of poker with Uno cards.",
    "%s can divide by zero and get a remainder.",
    "%s once made a weeping willow laugh.",
    "%s can watch 60 minutes in 20 seconds.",
    "When %s crosses the street, the cars stop and look both ways.",
    "%s can lift a ton with one finger...their pinky.",
    "%s doesn't measure things; things adjust to %s's preferences.",
    "%s once made the Mona Lisa frown.",
    "%s can draw a straight line with a ruler—without using the ruler.",
    "%s doesn’t need a parachute to skydive. He just decides when to land.",
    "%s’s calendar skips April Fool’s Day—because no one fools %s.",
    "%s can unscramble a scrambled channel on TV.",
    "%s doesn’t need keys to open doors. Doors just unlock themselves for him.",
    "%s can turn off a light by clapping… with one hand.",
    "%s can parallel park a train.",
    "%s can put out a fire using gasoline.",
    "%s can win a marathon without taking a single step.",
    "%s once scored a goal in hockey. Without a puck.",
    "%s can split the atom—with his bare hands.",
    "%s can jump-start a car with his mind.",
    "%s’s voice can shatter glass, but only when he wants it to.",
    "%s can plug in a USB on the first try, every time.",
    "%s can play a game of tennis with the net still up.",
    "%s once threw a boomerang that never came back. The boomerang was scared.",
    "%s doesn’t need a GPS; the roads follow him.",
    "%s once won hide and seek against the entire world.",
    "%s can find Waldo in one look.",
    "When %s turns on a light, darkness gets out of his way.",
    "%s can roundhouse kick a tornado.",
    "%s can make time stand still by looking at the clock.",
    "%s’s reflection won’t look at him out of respect.",
    "%s can walk on water—and swim through land.",
    "%s can start a fire with water.",
    "%s can eat a whole cake before anyone has a chance to cut it.",
    "%s can whistle in all languages.",
    "%s doesn’t dodge bullets; bullets dodge %s.",
    "%s once beat gravity in an arm-wrestling match.",
    "%s can melt ice by staring at it.",
    "%s can remember the future.",
    "%s’s footprints alone can be sold as artwork.",
    "%s once bowled a perfect game—in mini-golf.",
    "%s can pick a lock using only a paperclip and a toothpick.",
    "%s's handshake has made professional boxers retire.",
    "%s can alphabetize numbers.",
    "%s once played Jenga with Mount Everest. It’s now the Himalayas.",
    "%s doesn’t shave. His beard naturally falls off when it’s time.",
    "%s once made a Happy Meal unhappy.",
    "%s can cut through a hot knife with butter.",
    "%s can tie his shoes with his feet.",
    "%s once made an onion cry just by smiling at it.",
    "%s can do a full push-up without bending his arms.",
    "%s can touch time.",
    "%s doesn't wait for opportunity to knock; he knocks opportunity down.",
    "%s can turn invisible simply by standing still.",
    "%s once won an Olympic gold medal without competing.",
    "%s doesn’t need a ladder; the sky lowers for him.",
    "%s can win a staring contest with the sun.",
    "%s once squeezed orange juice out of an apple.",
    "%s can tune a piano by snapping his fingers.",
    "%s once turned a diamond back into coal—just because.",
    "%s doesn't do yoga; the universe stretches to accommodate him.",
    "%s can fold a fitted sheet perfectly in seconds.",
    "%s can find the square root of a negative number.",
    "%s can solve a maze by looking at it.",
    "%s’s phone never drops calls—it drops networks.",
    "%s doesn’t go to the gym. The gym comes to him.",
    "%s can stop traffic—by blinking.",
    "%s can microwave a steak with cold air.",
    "%s can solve a crossword puzzle without reading the clues.",
    "%s doesn’t iron his clothes; his body heat presses them perfectly.",
    "%s’s handshake once turned a rock into sand.",
    "%s can win a game of Monopoly with one roll of the dice.",
    "%s can sneeze with his mouth closed.",
    "%s can clap with one hand.",
    "%s once ran around the world just to see himself finish the race.",
    "%s’s frown can move mountains.",
    "%s can sneeze and burp at the same time—and remain composed.",
    "%s can speak all languages, even the ones that don’t exist yet.",
    "%s can stop a hurricane by blowing a kiss.",
    "%s can open a locked door with just a glance.",
    "%s doesn’t need maps; the earth arranges itself for him.",
    "%s can make a diamond by squeezing carbon with his eyelids.",
    "%s can beatbox in perfect harmony.",
    "%s can divide by one and get zero—just to prove a point.",
    "%s can high-five himself and make it sound like thunder.",
    "%s can predict tomorrow’s weather, today.",
    "%s can turn paper into scissors by staring at it.",
    "%s can make water float in mid-air.",
    "%s can put a square peg into a round hole.",
    "%s once made a brick house out of straw.",
    "%s can win at chess in one move—with a checker.",
    "%s can paint the Mona Lisa using only finger paints.",
    "%s once played Russian Roulette with a fully loaded gun—and won.",
    "%s can run faster than light and still stop for a coffee break.",
    "%s can peel a banana using only his mind.",
    "%s doesn’t break a sweat; sweat breaks itself for %s.",
    "%s can type faster than a supercomputer can compute.",
    "%s can juggle fire—and water.",
    "%s can freeze time and still be early to an appointment.",
    "%s once built a snowman out of sand.",
    "%s doesn’t need a GPS; lost people find %s.",
    "%s’s smile can power a city for a week.",
    "%s can turn glass back into sand.",
    "%s can create a black hole just by flexing.",
    "%s can make the sky blue by whistling.",
    "%s can flip a coin and make it land on its edge.",
    "%s can swim through lava and not get burned.",
    "%s can make time go backward by taking a step forward.",
    "%s can turn a cactus into a rose bush with a wink.",
    "%s can play ping-pong with a bowling ball.",
    "%s can drink boiling water and turn it into ice.",
    "%s can turn coal into diamonds with a gentle hug.",
    "%s once solved world hunger—by eating.",
    "%s can open a door just by knocking on the wall next to it.",
    "%s’s hair can cut through steel.",
    "%s can split the Red Sea with a smile.",
    "%s can jump to the moon and back before breakfast.",
    "%s can make the wind blow in any direction he chooses.",
    "%s can stop an avalanche by snapping his fingers.",
    "%s once gave CPR to a volcano and stopped it from erupting.",
    "%s can inflate a tire just by breathing on it.",
    "%s can watch a full season of a show in one episode.",
    "%s can make gravity take the day off.",
    "%s can knit a sweater out of fog.",
    "%s can boil water just by staring at it.",
    "%s can hear a pin drop from 10 miles away.",
    "%s can fly, but he doesn’t need to—he lets the air carry him.",
    "%s can bake a cake just by looking at an oven.",
    "%s doesn’t need a mirror; his reflection checks itself.",
    "%s can climb a tree and pick fruit from the roots.",
    "%s once won a staring contest with a brick wall.",
    "%s can walk through fire and make it apologize.",
    "%s once high-fived a cloud—and it rained.",
    "%s can turn sand into glass by clapping his hands.",
    "%s can walk on the ceiling without falling.",
    "%s’s dreams are the source of inspiration for movies.",
    "%s can surf on dry land.",
    "%s can melt steel with his kindness.",
    "%s can walk on water—and turn it into wine.",
    "%s can make popcorn without using heat.",
    "%s can break a diamond with his smile.",
    "%s can solve a jigsaw puzzle without looking at the pieces.",
    "%s can turn a light bulb on without touching the switch.",
    "%s can jump higher than a skyscraper.",
    "%s can skip rocks on land.",
    "%s can make a rainbow at night.",
    "%s can tame a lion with a whisper.",
    "%s can make a compass point wherever he wants.",
    "%s doesn’t catch fish; fish catch %s.",
    "%s can lift a mountain with one hand tied behind his back.",
    "%s can play the guitar with one string—and still sound better than anyone.",
    "%s can microwave a frozen pizza with a cold stare.",
    "%s can make a clock tick backward.",
    "%s can swim up a waterfall.",
    "%s can write a best-selling novel using only emojis.",
    "%s can solve any problem by snapping his fingers.",
    "%s can drive a car by thinking about it.",
    "%s can make a plant grow just by walking past it.",
    "%s doesn’t need sunscreen; the sun shields itself from him.",
    "%s can make a rainbow without rain.",
    "%s can erase a chalkboard without touching it.",
    "%s can stop a tornado by holding up his hand.",
    "%s doesn’t turn off lights; they go off out of respect.",
    "%s can tune a guitar just by humming.",
    "%s can win an argument without saying a word.",
    "%s once played hide-and-seek with the universe—and won.",
    "%s can turn air into water just by breathing.",
    "%s can stop a clock by smiling at it.",
    "%s can turn a frown upside down—literally.",
    "%s once played darts with a boomerang.",
    "%s can make a stone skip across an ocean.",
    "%s can ride a bicycle up a vertical wall.",
    "%s can make a lemon sweet with just a thought.",
    "%s doesn’t need a remote; the TV knows what he wants to watch.",
    "%s can walk through walls without leaving a trace.",
    "%s can melt ice with his charm alone.",
    "%s can win a staring contest with a mirror.",
    "%s can make the wind blow in reverse.",
    "%s can make the sun rise an hour early just by waking up.",
    "%s can fly faster than sound—and quieter than silence.",
    "%s once made a snowstorm in the desert.",
    "%s can turn a desert into an oasis just by snapping his fingers.",
    "%s can solve a math problem before it’s even written.",
    "%s can row a boat without water.",
    "%s can tame a wild animal by winking at it.",
    "%s can jump into space—and land softly.",
    "%s once ran a marathon in flip-flops—and won.",
    "%s can create art with a single stroke.",
    "%s can catch lightning in a bottle.",
    "%s can lift a boulder by smiling at it.",
    "%s once built a house with no tools. It now stands as a historical landmark.",
    "%s can bend spoons with his thoughts. Then he straightens them back for fun.",
    "%s once sneezed and caused a typhoon on the other side of the world.",
    "%s can juggle planets and still have a hand free for coffee.",
    "%s doesn't need to reload in a video game. The ammo reloads itself out of fear.",
    "%s once threw a snowball in the desert. Now that desert is an ocean.",
    "%s can play chess in 3D and win in 2 moves.",
    "%s’s GPS always follows him.",
    "%s can run so fast he catches up to himself.",
    "%s’s laugh can cure insomnia.",
    "%s once sneezed, and it echoed across the galaxy.",
    "%s can make a river flow uphill.",
    "%s can tell you the exact number of grains of sand on any beach.",
    "%s once took a selfie and the camera captured his awesomeness in 4D.",
    "%s can build a spaceship out of Legos and fly to Mars.",
    "%s can solve world hunger with a single thought. He’s just waiting for the right moment.",
    "%s once lifted the Great Wall of China to find his lost pen.",
    "%s’s footprints don’t leave a mark; they create artwork.",
    "%s can out-dance the wind.",
    "%s once stopped an earthquake by stomping his foot.",
    "%s can play the piano without touching it.",
    "%s can make diamonds out of dust just by winking.",
    "%s’s shadow once won a marathon.",
    "%s can silence thunder with a whisper.",
    "%s can paint a masterpiece with his breath.",
    "%s can teleport by thinking about it.",
    "%s can turn coal into gold with a smile.",
    "%s can clap his hands and part the clouds.",
    "%s can play soccer with a pebble and win the World Cup.",
    "%s can blow bubbles in space.",
    "%s once yawned and created a new galaxy.",
    "%s doesn’t fly; the Earth moves for him.",
    "%s can make volcanoes erupt with a blink.",
    "%s can make a mirror reflect his future self.",
    "%s can solve complex math problems just by nodding.",
    "%s can walk through walls and leave no trace.",
    "%s once wrote a poem so perfect it became a language.",
    "%s can climb a mountain without moving his legs.",
    "%s can sail a ship on dry land.",
    "%s can turn lead into gold just by thinking about it.",
    "%s can walk through a tornado without messing up his hair.",
    "%s’s signature is the reason ink exists.",
    "%s can whistle in space.",
    "%s doesn’t sleep; he power naps the universe.",
    "%s can stop an avalanche by snapping his fingers.",
    "%s can run faster than a speeding bullet—while walking.",
    "%s can balance the Earth on the tip of his finger.",
    "%s’s yawn once caused a solar eclipse.",
    "%s once blinked and the world skipped a second.",
    "%s can make fire from ice by simply staring at it.",
    "%s doesn’t need an umbrella; the rain stops for him.",
    "%s once taught a rock to swim.",
    "%s’s name is carved into the moon. You just haven’t noticed it yet.",
    "%s can turn a desert into a rainforest with a thought.",
    "%s’s voice can make plants grow instantly.",
    "%s once walked around the world in a single step.",
    "%s can stop a meteor with his pinky finger.",
    "%s can juggle stars without dropping one.",
    "%s’s reflection once gave him a standing ovation.",
    "%s can hear a snowflake fall.",
    "%s can play hopscotch on the moon without a spacesuit.",
    "%s can make the ocean part with a single word.",
    "%s’s tears cure droughts—too bad he never cries.",
    "%s once convinced the tides to switch directions.",
    "%s can play all musical instruments—simultaneously.",
    "%s can make lightning strike twice in the same place—just for fun.",
    "%s can play chess with the wind and always win.",
    "%s’s footsteps echo in other dimensions.",
    "%s once held a star in his hand and didn’t get burned.",
    "%s’s breath is the reason we have the atmosphere.",
    "%s can communicate with animals without speaking.",
    "%s once solved world peace by snapping his fingers.",
    "%s can make a tree grow in seconds.",
    "%s can move mountains just by thinking about it.",
    "%s can sing so beautifully, even birds take lessons from him.",
    "%s’s sneeze once caused the Big Bang.",
    "%s can skip a stone across a black hole.",
    "%s’s laughter can power a city for a year.",
    "%s can outrun a thought.",
    "%s’s shadow has a shadow of its own.",
    "%s once turned night into day with a clap of his hands.",
    "%s can make a rainbow without rain or sun.",
    "%s can climb a waterfall going up.",
    "%s can hear the future.",
    "%s can play hide and seek with the universe.",
    "%s can turn gravity off just by snapping his fingers.",
    "%s’s reflection once asked him for an autograph.",
    "%s can freeze time just by standing still.",
    "%s can find the North Star in the middle of the day.",
    "%s’s smile once calmed a hurricane.",
    "%s can change the color of the sky just by blinking.",
    "%s’s shadow once won the Tour de France.",
    "%s can make a river run backwards with a thought.",
    "%s can whistle in perfect harmony with himself.",
    "%s’s touch can turn metal into silk.",
    "%s can run across the ocean without getting wet.",
    "%s can control the wind with a wave of his hand.",
    "%s’s voice can calm the fiercest storm.",
    "%s can make a blizzard stop with a wink.",
    "%s once played chess against a supercomputer—and the computer forfeited.",
    "%s’s name is written in the stars.",
    "%s can swim faster than a fish.",
    "%s can climb a mountain without taking a step.",
    "%s once turned day into night with a smile.",
    "%s can hear the sound of silence.",
    "%s’s breath once created a new species of flower.",
    "%s can make the seasons change with a single thought.",
    "%s can paint the sky with his imagination.",
    "%s’s whisper can create a tornado.",
    "%s can make lightning strike on command.",
    "%s’s footsteps create earthquakes—but only when he allows it.",
    "%s can part the clouds with a flick of his wrist.",
    "%s can dance with the stars and not miss a beat.",
    "%s’s smile once created a new constellation.",
    "%s can balance a mountain on his finger.",
    "%s can make the Earth spin faster or slower as he pleases.",
    "%s can walk through fire and not get burned.",
    "%s once convinced the sun to rise an hour early.",
    "%s can change the course of a river just by thinking about it.",
    "%s’s laugh can make flowers bloom.",
    "%s can make the stars shine brighter with a wink.",
    "%s can juggle lightning bolts.",
    "%s once bent a rainbow into a circle.",
    "%s can run so fast he leaves footprints in the air.",
    "%s’s reflection is a work of art.",
    "%s can jump to the moon and back before breakfast.",
    "%s’s presence makes the air feel lighter.",
    "%s can play catch with a comet.",
    "%s can stop a volcano from erupting with a look.",
    "%s’s thoughts are the reason the universe exists.",
    "%s can make time stand still with a smile.",
    "%s’s shadow once climbed Mount Everest.",
    "%s can make a thunderstorm stop with a whisper.",
    "%s can turn the desert into a rainforest with a thought.",
    "%s can create an eclipse just by thinking about it.",
    "%s can make the stars twinkle on command.",
    "%s’s sneeze once shook the Earth’s core.",
    "%s can calm the ocean with a breath.",
    "%s’s voice can make the mountains echo.",
    "%s can make the planets align just by asking.",
    "%s can walk through a snowstorm and leave no footprints.",
    "%s can make a tree grow just by looking at it.",
    "%s can make the wind change direction with a thought.",
    "%s can make the Northern Lights dance with a smile.",
    "%s can create a snowstorm in the desert.",
    "%s’s touch can turn water into ice.",
    "%s’s reflection once gave him a standing ovation.",
    "%s can make gravity stop just by thinking about it.",
    "%s’s name is written in the stars.",
    "%s can part the clouds with a wink.",
    "%s’s shadow once won a marathon.",
    "%s can walk on lava without getting burned.",
    "%s’s smile can make the sun shine brighter.",
    "%s can stop a landslide with a look.",
    "%s can create a blizzard in the middle of summer.",
    "%s’s thoughts are so powerful they can move mountains.",
    "%s can turn a thunderstorm into a gentle rain.",
    "%s can make the stars align with a single word.",
    "%s can create an oasis in the desert with a smile.",
    "%s can walk through a hurricane and come out dry.",
    "%s can make time speed up or slow down as he pleases.",
    "%s’s voice can make the wind sing.",
    "%s can juggle planets without breaking a sweat.",
    "%s can make the sun rise an hour early with a thought.",
    "%s can part the Red Sea with a look.",
    "%s can make the stars shine brighter with a thought.",
    "%s can walk on air and leave footprints.",
    "%s can make the Earth rotate faster or slower with a smile.",
    "%s can create a snowstorm in the middle of summer.",
    "%s’s name is written in the stars.",
}
-- Assign the jokes table to the global scope
_G.jokes = jokes
