local jokes = {
  "When God said, 'Let there be light!' %s said, 'Say Please.'",
  "Since 1940, the year %s was born, roundhouse kick related deaths have increased 13,000 percent.",
  "If you spell %s in Scrabble, you win. Forever.",
  "Time waits for no man. Unless that man is %s.",
  "%s can have both feet on the ground and kick butt at the same time.",
  "Champions are the breakfast of %s.",
  "%s can play the violin with a piano.",
  "%s drinks napalm to fight his heartburn.",
  "The earth used to be flat, until %s told it to roll over.",
  "%s's parents go to his room when they had a bad dream.",
  "%s knows what is on the other side of a black hole.",
  "%s passed 6 kidney stones. Thanos tried to collect them all.",
  "When Facebook was invented, Zuckerburg had a friend request from %s.",
  "%s gets up so early that it is still yesterday.",
  "%s was skipping stones on a lake one day, then the dinosaurs went extinct.",
  "When %s tells a joke about Jada Smith, Will Smith stands up and slaps Jada.",
  "%s knows when Santa is sleeping, and knows when he is awake.",
  "%s died 20 years ago, Death just hasn't had the courage to tell him.",
  "%s was able to find the page '404'.",
  "Alexander Graham Bell had two missed calls from %s when he invented the phone.",
  "%s once met Stephen Hawking. Stephen stood up so %s could sit down.",
  "%s only lifts weights to give gravity a break.",
  "%s can't tell jokes, no one would survive the punch line.",
  "While learning CPR, %s brought the dummy back to life.",
  "%s was born in the hospital that was named after him.",
  "%s told his alarm to wake up at 6.",
  "%s has a diary, it is called the Guinness Book of World Records.",
  "%s taught a book how to read",
  "%s isn't the chosen one. He chooses the chosen one.",
  "%s built sand castles as a kid, we know them as the pyramids",
  "%s can read QR codes.",
  "%s uses stunt doubles, but only for the crying parts",
  "%s doesn't flush the toilet, he just scares the crap out of it.",
  "%s once threw a grenade and killed 50 men. Then the grenade exploded.",
  "%s once arm wrestled Superman. The loser had to wear their underwear on the outside of their pants.",
  "%s doesn't have a reflection, because there is only one %s.",
  "%s was in all of the Star Wars movies and spinnoffs. He played The Force.",
  "They once tried to name a bridge after %s, but changed their mind because no one crosses %s.",
  "When ghosts go camping, they tell %s stories",
  "%s once beat a dead man to life.",
  "When %s moved out of his parent's house, he told his dad that he was the man of the hosue now",
  "How many pushups can %s do? All of them.",
  "%s can see John Cena.",
  "%s once karate chopped a boulder in half. It is known as the Grand Canyon.",
  "%s introduced his grandparents to each other.",
  "When %s gets cut by a knife, the knife bleeds.",
  "Love once looked %s in the eyes, now love is blind.",
  "If you have 5 gold and %s has 5 gold, %s has more gold than you.",
  "%s once heard nothing can kill him, so he tracked down nothing and killed it.",
  "%s was born with 15 balls but donated the extra 13. You know the first 7 as the Dragon Balls, and the other 6 as the Infinity Stones.",
  "%s once rubbed two fires together to make a stick.",
  "%s doesn't walk or run. The earth moves for him.",
  "%s wears sunscreen to protect the sun.",
  "%s doesn't read books. He stares them down until they give up their information.",
  "%s counted to infinity... twice.",
  "When the Boogeyman goes to sleep every night, he checks his closet for %s.",
  "%s can divide by zero.",
  "%s can slam a revolving door.",
  "%s's tears cure cancer. Too bad %s has never cried.",
  "%s once kicked a horse in the chin. Its descendants are known today as giraffes.",
  "%s doesn't wear a watch. He decides what time it is.",
  "%s can hear sign language.",
  "Death once had a near-%s experience.",
  "%s makes onions cry.",
  "%s can strangle you with a cordless phone.",
  "%s once won a game of Connect Four in three moves.",
  "%s can kill two stones with one bird.",
  "%s doesn't mow his lawn. He dares it to grow.",
  "The flu gets a %s shot every year.",
  "%s beat the sun in a staring contest.",
  "%s can dribble a bowling ball.",
  "%s's calendar goes straight from March 31st to April 2nd. No one fools %s.",
  "%s can speak braille.",
  "%s's house has no doors, only walls that he walks through.",
  "%s once got bit by a cobra. After five days of excruciating pain, the cobra died.",
  "%s doesn't dial the wrong number. You pick up the wrong phone.",
  "%s can sneeze with his eyes open.",
  "%s's blood type is AK-47.",
  "%s once won a staring contest with his own reflection.",
  "When %s does push-ups, he isn't lifting himself up; he's pushing the Earth down.",
  "%s can light a fire by rubbing two ice cubes together.",
  "%s's dog picks up his own poop because %s doesn't take crap from anyone.",
  "%s's computer doesn't have a 'backspace' key because %s doesn't make mistakes.",
  "%s once ordered a steak in a vegan restaurant—and got it.",
  "%s can do a wheelie on a unicycle.",
  "%s doesn't need a keyboard to press Ctrl+Alt+Delete.",
  "%s once scared a hurricane into staying out at sea.",
  "%s's shadow has never been seen.",
  "%s can build a snowman out of rain.",
  "%s once won the World Series of Poker using UNO cards.",
  "%s can grill a popsicle.",
  "%s's sweat is the cure for the common cold.",
  "%s doesn't flush the toilet; he scares the crap out of it.",
  "%s once punched a cyclops between the eye.",
  "%s can drown a fish.",
  "%s once had a heart attack; his heart lost.",
  "%s can unscramble an egg.",
  "%s knows Victoria's secret.",
  "%s's smile once brought a puppy back to life.",
  "%s can gargle peanut butter.",
  "%s once won a race against light.",
  "%s can make a slinky go upstairs.",
  "%s's handshake is the equivalent of a lightning strike.",
  "%s once won a staring contest with the sun.",
  "%s can pick oranges from an apple tree and make the best lemonade you've ever tasted.",
  "%s once kicked the Earth and it hasn't stopped spinning since.",
  "%s can clap with one hand.",
  "%s doesn't get sunburned; the sun gets %s-burned.",
  "%s can hear colors and see sounds.",
  "When %s was born, he drove his mom home from the hospital.",
  "%s can make a snowball out of rain.",
  "%s doesn't need to sleep; sleep needs %s.",
  "%s can start a fire with a magnifying glass—at night.",
  "%s once beat the moon in a staring contest.",
  "%s can squeeze orange juice out of a lemon.",
  "%s's reflection looks away out of fear.",
  "%s doesn't breathe; he holds air hostage.",
  "%s can tie his shoes with his feet.",
  "%s doesn't need a parachute; the ground comes up to meet him softly.",
  "%s can unscramble scrambled eggs.",
  "%s can kill time without injuring eternity.",
  "%s once challenged his own shadow to a fight. It lost.",
  "%s can hear a pin drop from miles away.",
  "%s doesn't wear shoes; the earth protects his feet.",
  "%s's watch runs on his own time.",
  "%s doesn't need a GPS; he decides where he is.",
  "%s can fold paper more than seven times.",
  "%s doesn't catch colds; colds catch %s.",
  "%s can solve a Rubik's Cube with one hand tied behind his back.",
  "%s doesn't age; time gets old waiting for %s.",
  "%s can whistle in all languages.",
  "%s once got pulled over for speeding, but let the cop go with a warning.",
  "%s can count to infinity backwards.",
  "%s can delete the Recycling Bin.",
  "%s doesn't need to read; words assemble themselves in his mind.",
  "%s can set ants on fire with a magnifying glass. At night.",
  "%s once won a game of rock-paper-scissors using only rock.",
  "%s can touch this.",
  "%s doesn't swim; water moves around him.",
  "%s doesn't get frostbite; frost gets %s-bite.",
}
_G.jokes = jokes
